name: Build SDK

on:
  push:
    branches:
      - main
    paths:
      - "apps/mobile/**"
    tags:
      - "sdk-v*"
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build-sdk:
    name: Build and publish Expo SDK artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile --filter ./apps/mobile

      - name: Prepare SDK tarball from Expo app
        id: pack
        working-directory: apps/mobile
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          SAFE_NAME=${NAME//@/}
          SAFE_NAME=${SAFE_NAME//\//-}
          TAR_NAME=${SAFE_NAME}-${VERSION}.tgz
          tar --exclude='node_modules' --exclude='.git' --exclude-vcs -czf "../${TAR_NAME}" .
          echo "tarball=apps/${TAR_NAME}" >> $GITHUB_OUTPUT

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-sdk
          path: ${{ steps.pack.outputs.tarball }}

      - name: Publish GitHub Release (on tags only)
        if: startsWith(github.ref, 'refs/tags/sdk-v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          draft: false
          artifacts: ${{ steps.pack.outputs.tarball }}
          artifactErrorsFailBuild: true
