name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile --filter '@commit/api' --filter '@commit/types'

      - name: Lint API
        run: pnpm --filter '@commit/api' run lint

      - name: Test API
        run: pnpm --filter '@commit/api' run test

      - name: Deploy to Cloudflare Workers (Wrangler)
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CI: true
        run: pnpm run deploy:production

      - name: Apply database migrations
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CI: true
        run: pnpm run db:migrate:production
